#  This file is part of Ydle.
#
#    Ydle is free software: you can redistribute it and/or modify
#    it under the terms of the GNU  Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Ydle is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU  Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with Ydle.  If not, see <http://www.gnu.org/licenses/>.
    
################
#    Nodes     #
################    
nodes:
    pattern:  /nodes
    defaults: { _controller: YdleNodesBundle:Nodes:index }    
nodeAdd:
    pattern:  /nodes/add
    defaults: { _controller: YdleNodesBundle:Nodes:form }
nodeEdit:
    pattern:  /nodes/edit/{node}
    defaults: { _controller: YdleNodesBundle:Nodes:form, room:0 }
nodeDelete:
    pattern:  /nodes/delete/{node}
    defaults: { _controller: YdleNodesBundle:Nodes:delete, node:0 } 
nodeActivation:
    pattern:  /nodes/activation/{node}/{active}
    defaults: { _controller: YdleNodesBundle:Nodes:activation, node:0, active:0 }  
nodeInitialize:
    pattern:  /nodes/initialize/{node}/{active}
    defaults: { _controller: YdleNodesBundle:Nodes:initialize, node:0, active:0 }  
nodeReset:
    pattern:  /nodes/reset/{node}
    defaults: { _controller: YdleNodesBundle:Nodes:reset, node:0 }   
nodeLink:
    pattern:  /nodes/link/{node}
    defaults: { _controller: YdleNodesBundle:Nodes:link, node:0 } 
nodeSensors:
    pattern:  /nodes/sensors/{node}
    defaults: { _controller: YdleNodesBundle:Nodes:sensors, node:0 } 
    
##################
#  Type Sensors  #
##################
configTypeSensor:
    pattern:  /conf/typesensor/{type}
    defaults: { _controller: YdleIhmBundle:Config:typesensor, type:0 }
configTypeSensorActivation:
    pattern:  /conf/typesensor/activation/{type}/{active}
    defaults: { _controller: YdleIhmBundle:Config:typesensoractivation, type:0, active:0 } 
configTypeSensorDelete:
    pattern:  /conf/typesensor/delete/{type}
    defaults: { _controller: YdleIhmBundle:Config:typesensordelete, type:0 } 